export const START_LOADING = "START_LOADING"
export const LOADING_SUCCESS = "LOADING_SUCCESS"
export const LOADING_FAILED = "LOADING_FAILED"
export const LOAD_CONTACTS = "LOAD_CONTACTS"
export const ACCESS_LOAD_CONTACTS = "ACCESS_LOAD_CONTACTS"
export const ACCESS_CALL = "ACCESS_CALL"
export const SHOW_AD = "SHOW_AD"

